
// SAGA -> RUDUX
export const AT_DISPLAY_ACTION = 'AT_DISPLAY_ACTION';
export const AT_SQLITE_DB_OPEN_START = 'AT_SQLITE_DB_OPEN_START';
export const AT_SQLITE_DB_OPEN_SUCCESS = 'AT_SQLITE_DB_OPEN_SUCCESS';
export const AT_SQLITE_MAIN_DATA_READ_START = 'AT_SQLITE_MAIN_DATA_READ_START';
export const AT_SQLITE_MAIN_DATA_READ_SUCCESS = 'AT_SQLITE_MAIN_DATA_READ_SUCCESS';

// DIRECT RUDUX

// OTHER
export const IS_LOADING = 'IS_LOADING...';
